apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-info-ingress
  namespace: production
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=production,Team=linkedin-learning
  # Remove classname annotation
    alb.ingress.kubernetes.io/use-regex: "true"
  

spec:
  ingressClassName: alb
  # Add INGRESSCLASSNAME FIELD
  rules:
    - http:
        paths:
          - path: /?(.*) # Use regex to match root and any subpath
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-cluster-ip-service 
                port:
                  number: 5000 